Feature1
gurbuzertunga/youtubeclone pull request #1
Opened 2020-07-08 07:06 UTC by gurbuzertunga

2020-07-08 07:09 UTC, gurbuzertunga commented
@dasileker can you review my code?

2020-07-08 07:09 UTC, lirad commented
Testing reviewing

2020-07-08 07:09 UTC, gurbuzertunga commented
@DcRonan can you review my code?

2020-07-08 07:16 UTC, lirad commented on index.html
>      <head>
Add  a header tag and check this article about the <head> tag https://www.w3schools.com/tags/tag_head.asp

2020-07-08 07:17 UTC, DcRonan requested changes

2020-07-08 07:17 UTC, DcRonan commented on index.html
> +       <h4 color="gray">7.578.549 views</h4>
The full stops should be commas.

2020-07-08 07:22 UTC, DcRonan requested changes

2020-07-08 07:22 UTC, DcRonan commented on index.html
> +        </nav>
The code above including the images, div, input and button should be in the body tag and not the head tag.

2020-07-08 07:23 UTC, lirad commented on index.html
> +            <div class="weirdbuttons">
lol, funny name to a class

2020-07-08 07:24 UTC, lirad commented on index.html
> +                <div id="viewcount"><h4 color="gray">7.578.549 views</h4></div>
as suggestion use either camelCase or a dash separated naming style ex: view-count or viewCount

2020-07-08 07:27 UTC, gurbuzertunga commented
@oracleot can you review my code?

2020-07-08 07:28 UTC, lirad commented
Try to normalize the CSS first so it will be compatible between browsers: https://meyerweb.com/eric/tools/css/reset/

2020-07-08 07:31 UTC, oracleot commented
Try to use more of semantic HTML elements:
https://www.w3schools.com/html/html5_semantic_elements.asp

2020-07-29 06:56 UTC, RICKCOYL approved these changes

2020-07-30 14:19 UTC, merged